language:
  node_js
node_js:
  - stable
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_TOKEN
  app: canvas-shapes
  on:
    repo: pedrofurst/shapes
    branch: master
